### ISSUE TITLE
Deploy to maven central

### ISSUE THREAD

**Issue by safris** [thibaultmeyer/cuid-java#1]
I found this repo mentioned in https://usecuid.org/. It would be great if this library could be automatically deployed to Maven Central repo, so that people could reference it as a Maven dependency.

**Comment by thibaultmeyer** [comment]
Hello,

very good idea, I will look into adding this library on Maven Central.

**Comment by thibaultmeyer** [comment]
Library just published on OSS SonaType / Maven Central.

```xml
<dependency>
    <groupId>io.github.thibaultmeyer</groupId>
    <artifactId>cuid</artifactId>
    <version>1.0.0</version>
</dependency>
```
