### ISSUE TITLE
Cuid standard is deprecated.

### ISSUE THREAD

**Issue by ericelliott** [thibaultmeyer/cuid-java#2]
Due to security concerns (which also exist in database auto-increment ids, uuid/guid, and most other id standrads), the Cuid standard is now deprecated in favor of [Cuid2](https://github.com/paralleldrive/cuid2).

**Comment by thibaultmeyer** [comment]
Version 2.0.0 now can generate CUID v2 (CUID v1 has been keep for retro-compatibility)
