### ISSUE TITLE
Please Support Parameterized Length

### ISSUE THREAD

**Issue by IamManchanda** [thibaultmeyer/cuid-java#4]
**Is your feature request related to a problem? Please describe.**
When the use-case is simply something like username or URL disambiguation where you don't need strong uniqueness guarantees.

**Describe the solution you'd like**
Parameterized Length in CUID 2 https://github.com/paralleldrive/cuid2#parameterized-length

**Describe alternatives you've considered**
N/A

**Additional context**
official javascript example of same

```javascript
import { init } from '@paralleldrive/cuid2';
const length = 10; // 50% odds of collision after ~51,386,368 ids
const cuid = init({ length });
console.log(cuid()); // nw8zzfaa4v
```

**Comment by IamManchanda** [comment]
@thibaultmeyer - FWIW, I was looking at the code and I think this can be made public https://github.com/thibaultmeyer/cuid-java/blob/release/2.0.0/src/main/java/io/github/thibaultmeyer/cuid/CUID.java#L72 for same ... or maybe you would want some init configuration ... let me leave it upon you :)

**Comment by thibaultmeyer** [comment]
Hi @IamManchanda,

This is exactly the solution I chose to meet the request. A new version should be available within 1 or 2 hours on Maven Central.

**Comment by IamManchanda** [comment]
Great to know @thibaultmeyer 🙏👌🙌

**Comment by IamManchanda** [comment]
@thibaultmeyer - Please don't mind but did you push the release to Maven Central?
as not yet available https://mvnrepository.com/artifact/io.github.thibaultmeyer/cuid as of now
(neither able to install it in my IntelliJ)

**Comment by thibaultmeyer** [comment]
@IamManchanda

mvnrepository is not "real time", new version will appear in few hours.

```xml
<dependency>
    <groupId>io.github.thibaultmeyer</groupId>
    <artifactId>cuid</artifactId>
    <version>2.0.1</version>
</dependency>
```

I just try on a dummy project, no problem, IntelliJ download jar from Maven Central.

```
Downloading from central: https://repo.maven.apache.org/maven2/io/github/thibaultmeyer/cuid/2.0.1/cuid-2.0.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/io/github/thibaultmeyer/cuid/2.0.1/cuid-2.0.1.pom (6.7 kB at 25 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/github/thibaultmeyer/cuid/2.0.1/cuid-2.0.1.jar
Downloaded from central: https://repo.maven.apache.org/maven2/io/github/thibaultmeyer/cuid/2.0.1/cuid-2.0.1.jar (11 kB at 130 kB/s)
```

**Comment by JamoCA** [comment]
So the change to return a "Parameterized Length" simply involves performing a left trim at `X` characters?  That's a simple string function that can be performed post-CUID without having to upgrade the library, right?

**Comment by IamManchanda** [comment]
Thanks @thibaultmeyer ... It's working now since last 24-30 hours... thank you :)

**Comment by IamManchanda** [comment]
@JamoCA - Now this library supports both these ways to generate CUID v2

```java
final CUID cuid = CUID.randomCUID2();
System.out.println("CUID (Version 2): " + cuid); // default 24 chars
```

and also

```java
final CUID cuid32 = CUID.randomCUID2(32); // or whatever number you wanna add
System.out.println("CUID (Version 2), 32: " + cuid32); // 32 chars
```

PS: I do think Github Readme should be updated to let devs know of this new addition

**Comment by thibaultmeyer** [comment]
Yes I will update the readme

**Comment by thibaultmeyer** [comment]
Done

**Comment by IamManchanda** [comment]
Thanks @thibaultmeyer 👍🙏
