### ISSUE TITLE
Please provide validation `isCuid` feature provided by Cuid v2.2.0 (Upstream, Official JS)

### ISSUE THREAD

**Issue by IamManchanda** [thibaultmeyer/cuid-java#5]
**Is your feature request related to a problem? Please describe.**
https://github.com/paralleldrive/cuid2#validation

```javascript
import { createId, isCuid } from '@paralleldrive/cuid2';

console.log(
  isCuid(createId()), // true
  isCuid('not a cuid'), // false
);
```

**Describe the solution you'd like**
Java version of https://github.com/paralleldrive/cuid2/pull/38/files

**Describe alternatives you've considered**
N/A

**Additional context**
https://github.com/paralleldrive/cuid2/issues/37
https://github.com/paralleldrive/cuid2/pull/38
https://github.com/paralleldrive/cuid2/releases/tag/v2.2.0

**Comment by thibaultmeyer** [comment]
Hello,

The static method `CUID::isValid` is available since the version 1.0.0. It should meet your needs. But I must admit that it has no unit tests. This method is implicitly tested via the unit tests of the `CUID::fromString`.

**Comment by IamManchanda** [comment]
Got it thanks, Can we update the Readme if it's already available besides if you want to implement unit tests ... thanks in advance 😃

**Comment by thibaultmeyer** [comment]
Yes, I will add tests on `CUID::isValid` method and update the `README.md` file.

I'll keep this issue open while I make the changes.

Thanks

**Comment by IamManchanda** [comment]
Sure let me wait for the updates, thank you so much 🙌
